import { DashboardCardProps, SortFilterItem } from "@/types";
import { formInputs, productInputs } from "./inputs";
export const sorting: SortFilterItem[] = [
  {
    title: "Trending",
    slug: "trending-desc",
    sortKey: "BEST_SELLING",
    reverse: false,
  }, // asc
  {
    title: "Latest arrivals",
    slug: "latest-desc",
    sortKey: "CREATED_AT",
    reverse: true,
  },
  {
    title: "Price: Low to high",
    slug: "price-asc",
    sortKey: "PRICE",
    reverse: false,
  }, // asc
  {
    title: "Price: High to low",
    slug: "price-desc",
    sortKey: "PRICE",
    reverse: true,
  },
];

const dashboardCards: DashboardCardProps[] = [
  {
    image: "/icons/order.svg",
    title: "Orders",
    number: "10",
    description: "+2",
    url: "/orders",
  },
  {
    image: "/icons/revenue.svg",
    title: "Revenue",
    number: "$1,200.59",
    url: "#",
    description: "+$150",
  },
  {
    image: "/icons/sales.svg",
    title: "Sales",
    number: "$5,000",
    url: "/sales",
    description: "+$2,000",
  },
  {
    image: "/icons/customers.svg",
    title: "Customers",
    number: "20",
    url: "#",
  },
  {
    image: "/icons/subscribers.svg",
    title: "Subscribers",
    number: "100",
    url: "#",
    description: "+2",
  },
  {
    image: "/icons/visits.svg",
    title: "Visits",
    number: "100",
    url: "#",
    description: "+20",
  },
  {
    image: "/icons/review.svg",
    title: "Reviews",
    number: "3.8",
    url: "/reviews",
    description: "-0.1",
  },
  {
    image: "/icons/products.svg",
    title: "Products",
    number: "100",
    url: "/products",
  },
  {
    image: "/icons/products.svg",
    title: "shipping",
    number: "100",
    url: "/shipping",
  },
  {
    image: "/icons/visits.svg",
    title: "Store",
    number: "100",
    url: "/store",
    description: "+20",
  },
  {
    image: "/icons/customers.svg",
    title: "Collection",
    number: "100",
    url: "/store/collections",
  },
];

const CSS_COLORS = [
  "aliceblue",
  "antiquewhite",
  "aqua",
  "aquamarine",
  "azure",
  "beige",
  "bisque",
  "black",
  "blanchedalmond",
  "blue",
  "blueviolet",
  "brown",
  "burlywood",
  "cadetblue",
  "chartreuse",
  "chocolate",
  "coral",
  "cornflowerblue",
  "cornsilk",
  "crimson",
  "cyan",
  "darkblue",
  "darkcyan",
  "darkgoldenrod",
  "darkgray",
  "darkgrey",
  "darkgreen",
  "darkkhaki",
  "darkmagenta",
  "darkolivegreen",
  "darkorange",
  "darkorchid",
  "darkred",
  "darksalmon",
  "darkseagreen",
  "darkslateblue",
  "darkslategray",
  "darkslategrey",
  "darkturquoise",
  "darkviolet",
  "deeppink",
  "deepskyblue",
  "dimgray",
  "dimgrey",
  "dodgerblue",
  "firebrick",
  "floralwhite",
  "forestgreen",
  "fuchsia",
  "gainsboro",
  "ghostwhite",
  "gold",
  "goldenrod",
  "gray",
  "grey",
  "green",
  "greenyellow",
  "honeydew",
  "hotpink",
  "indianred",
  "indigo",
  "ivory",
  "khaki",
  "lavender",
  "lavenderblush",
  "lawngreen",
  "lemonchiffon",
  "lightblue",
  "lightcoral",
  "lightcyan",
  "lightgoldenrodyellow",
  "lightgray",
  "lightgrey",
  "lightgreen",
  "lightpink",
  "lightsalmon",
  "lightseagreen",
  "lightskyblue",
  "lightslategray",
  "lightslategrey",
  "lightsteelblue",
  "lightyellow",
  "lime",
  "limegreen",
  "linen",
  "magenta",
  "maroon",
  "mediumaquamarine",
  "mediumblue",
  "mediumorchid",
  "mediumpurple",
  "mediumseagreen",
  "mediumslateblue",
  "mediumspringgreen",
  "mediumturquoise",
  "mediumvioletred",
  "midnightblue",
  "mintcream",
  "mistyrose",
  "moccasin",
  "navajowhite",
  "navy",
  "oldlace",
  "olive",
  "olivedrab",
  "orange",
  "orangered",
  "orchid",
  "palegoldenrod",
  "palegreen",
  "paleturquoise",
  "palevioletred",
  "papayawhip",
  "peachpuff",
  "peru",
  "pink",
  "plum",
  "powderblue",
  "purple",
  "red",
  "rosybrown",
  "royalblue",
  "saddlebrown",
  "salmon",
  "sandybrown",
  "seagreen",
  "seashell",
  "sienna",
  "silver",
  "skyblue",
  "slateblue",
  "slategray",
  "slategrey",
  "snow",
  "springgreen",
  "steelblue",
  "tan",
  "teal",
  "thistle",
  "tomato",
  "turquoise",
  "violet",
  "wheat",
  "white",
  "whitesmoke",
  "yellow",
  "yellowgreen",
];

const tags = {
  products: "products",
  collections: "collections",
  reviews: "reviews",
  navbarLinks: "navbarLinks",
  footer: "footer",
  stories: "stories",
  offers: "offers",
  properties: "properties",
  categories: "categories",
  coupons: "coupons",
  shipping: "shipping",
  store: "store",
};
export { tags, CSS_COLORS, dashboardCards, formInputs, productInputs };
